apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: taskmaster-pubsub
spec:
  type: pubsub.kafka
  version: v1
  metadata:
    - name: brokers
      value: "kafka:9092"
    - name: consumerGroup
      value: "taskmaster-group"
    - name: authType
      value: "none"
